use_frameworks!

platform :ios, '8.0'

target 'YYKeyboard_Example' do
  pod 'YYKeyboard', :path => '../'
  
  target 'YYKeyboard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
